export const slugs = ['home', 'about', 'services', 'plans', 'policies']
export const fields = {
  home: [['heroEyebrow','Hero eyebrow'],['heroTitle','Hero title'],['heroText','Hero description','long'],['gemTitle','GeM section title'],['gemText','GeM section description','long'],['stats','Case File stats','json'],['industries','Top industries','json'],['partners','Partner names','array'],['trainingHighlights','Training highlights','json'],['testimonials','Testimonials','json']],
  about: [['eyebrow','Eyebrow'],['title','Page title'],['intro','Intro','long'],['storyTitle','Story title'],['storyParagraphs','Story paragraphs','array'],['values','Values','array'],['mission','Mission','long'],['vision','Vision','long'],['differentiators','Why MA Creation cards','json'],['method','How we work steps','json'],['capabilities','Capability map','json'],['outcomes','Client outcomes','json'],['journeyEyebrow','Journey eyebrow'],['journeyTitle','Journey title'],['journeyText','Journey description','long'],['journey','GeM Journey stages','json'],['aiTools','AI Advantage tools','json'],['aiTitle','AI Advantage title'],['aiText','AI Advantage description','long'],['founderName','Founder name'],['founderRole','Founder role'],['founderBio','Founder bio','long'],['founderQuote','Founder quote','long'],['teamTitle','Team title'],['teamText','Team description','long'],['teamBullets','Team bullets','array'],['roadmapTitle','Roadmap title'],['roadmapText','Roadmap description','long'],['roadmap','Roadmap items','json']],
  services: [['eyebrow','Eyebrow'],['title','Page title'],['intro','Intro','long'],['pillarsTitle','Pillars title'],['pillars','Service pillars','json'],['sellerDocuments','Seller documents','array'],['buyerDocuments','Buyer documents','array']],
  plans: [['eyebrow','Eyebrow'],['title','Page title'],['intro','Intro','long'],['retainerEyebrow','Retainer eyebrow'],['retainerTitle','Retainer title'],['retainerNote','Retainer note','long'],['serviceEyebrow','Service packages eyebrow'],['serviceTitle','Service packages title'],['trainingEyebrow','Training eyebrow'],['trainingTitle','Training title']],
  policies: [['eyebrow','Eyebrow'],['title','Page title'],['termsTitle','Terms title'],['privacyTitle','Privacy title'],['refundTitle','Refund title'],['trainingTitle','Training title'],['terms','Terms','array'],['privacy','Privacy','array'],['refund','Refund','array'],['training','Training','array']]
}
export function showValue(value,type){if(type==='array')return Array.isArray(value)?value.join('\n'):'';if(type==='json')return JSON.stringify(value||[],null,2);return value??''}
export function parseValue(value,type){if(type==='array')return String(value).split('\n').map(x=>x.trim()).filter(Boolean);if(type==='json')return JSON.parse(value||'[]');return value}
