import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, setSession } from '../lib/api'

function PasswordField({ id, label, value, onChange }) { return <div><label className="field-label" htmlFor={id}>{label}</label><input id={id} type="password" value={value} onChange={e=>onChange(e.target.value)} required minLength={8} className="field-input" placeholder="Minimum 8 characters" /></div> }

export default function Login(){
 const [tab,setTab]=useState('login'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const navigate=useNavigate()
 const [login,setLogin]=useState({email:'',password:''}); const [register,setRegister]=useState({name:'',company:'',email:'',phone:'',interest:'GeM Registration',password:''})
 async function submit(e){e.preventDefault();setError('');setLoading(true);try{const data=await api(`/auth/${tab==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(tab==='login'?login:register)});setSession(data); navigate(data.user.role==='admin'?'/admin':'/')}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <section className="py-14 md:py-20 min-h-[calc(100vh-320px)] flex items-center"><div className="wrap w-full"><div className="max-w-[980px] mx-auto bg-card border border-ink/10 rounded-[10px] overflow-hidden shadow-card grid grid-cols-1 lg:grid-cols-2">
  <div className="bg-ink text-paper p-7 sm:p-11"><span className="eyebrow-light">Client Portal</span><h1 className="mt-3 font-display text-[34px] leading-tight">Your GeM case file,<br/>in one place.</h1><p className="mt-4 text-paper/65 text-[14.5px] max-w-[42ch]">Create an account to request services, track onboarding and access invoices, certificates and reports.</p><div className="mt-8 space-y-4">{['Request a service or demo','Stay connected with your consultant','Download invoices, certificates & reports'].map(t=><div key={t} className="flex gap-3 items-start"><span className="w-8 h-8 rounded-full border border-goldlight text-goldlight flex items-center justify-center shrink-0">✓</span><p className="text-sm text-paper/75">{t}</p></div>)}</div></div>
  <div className="p-6 sm:p-11"><div className="flex gap-1 bg-paper2 rounded p-1 mb-8"><button type="button" onClick={()=>setTab('login')} className={`flex-1 py-2.5 rounded text-sm font-semibold ${tab==='login'?'bg-card shadow-sm text-ink':'text-ink/60'}`}>Login</button><button type="button" onClick={()=>setTab('register')} className={`flex-1 py-2.5 rounded text-sm font-semibold ${tab==='register'?'bg-card shadow-sm text-ink':'text-ink/60'}`}>Register</button></div>
  {tab==='login'?<><h2 className="font-display text-[24px]">Welcome back</h2><p className="mt-1.5 text-ink/70 text-sm">Log in to your MA Creation account.</p><form onSubmit={submit} className="mt-6 space-y-4"><div><label className="field-label">Email</label><input className="field-input" type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></div><PasswordField id="login-password" label="Password" value={login.password} onChange={v=>setLogin({...login,password:v})}/><button className="btn-gold btn-block" disabled={loading}>{loading?'Signing in…':'Log In'}</button></form><p className="mt-5 text-sm text-ink/70">New to MA Creation? <button className="text-gold2 underline" onClick={()=>setTab('register')}>Create an account</button></p></>:<><h2 className="font-display text-[24px]">Create your account</h2><p className="mt-1.5 text-ink/70 text-sm">Set up your file and our team can follow up.</p><form onSubmit={submit} className="mt-6 space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="field-label">Full name</label><input className="field-input" value={register.name} onChange={e=>setRegister({...register,name:e.target.value})} required/></div><div><label className="field-label">Company</label><input className="field-input" value={register.company} onChange={e=>setRegister({...register,company:e.target.value})}/></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="field-label">Email</label><input className="field-input" type="email" value={register.email} onChange={e=>setRegister({...register,email:e.target.value})} required/></div><div><label className="field-label">Contact number</label><input className="field-input" value={register.phone} onChange={e=>setRegister({...register,phone:e.target.value})} required/></div></div><div><label className="field-label">I’m interested in</label><select className="field-input" value={register.interest} onChange={e=>setRegister({...register,interest:e.target.value})}><option>GeM Registration</option><option>Managed Retainer Plan</option><option>GeM Training Program</option><option>OEM / Vendor Support</option><option>Bid & Reverse Auction Support</option></select></div><PasswordField id="register-password" label="Create password" value={register.password} onChange={v=>setRegister({...register,password:v})}/><label className="flex items-start gap-2 text-xs text-ink/70"><input type="checkbox" required className="mt-0.5"/>I agree to the <Link to="/policies#terms" className="text-gold2 underline">Terms & Conditions</Link> and <Link to="/policies#privacy" className="text-gold2 underline">Privacy Policy</Link>.</label><button className="btn-gold btn-block" disabled={loading}>{loading?'Creating…':'Create Account'}</button></form><p className="mt-5 text-sm text-ink/70">Already registered? <button className="text-gold2 underline" onClick={()=>setTab('login')}>Log in</button></p></>}
  {error&&<div role="alert" className="mt-5 rounded border border-rust/30 bg-rust/5 px-4 py-3 text-sm text-rust">{error}</div>}
  </div></div></div></section>
}
